- include: base.yml
- include: master.yml  
  when: "is_hadoop_master == 'yes'"
- include: hive.yml
  when: "is_hadoop_master == 'yes'"
- include: slave.yml
  when: "is_hadoop_master != 'yes'"
- include: spark.yml
  when: "is_spark == 'yes'"


