- hosts: hadoop
  gather_facts: no
  tasks:
    - name: cdh5 repo
      apt_repository: repo='deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib' state=present
    - name: cdh5 contrib repo
      apt_repository: repo='deb-src http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib' state=present
    - name: install hadoop all packages
      apt: pkg={{ item }} state=latest force=yes 
      with_items:
        - hadoop-yarn-nodemanager
        - hadoop-hdfs-datanode
        - hadoop-mapreduce
- hosts: hadoopmaster
  tasks:
    - name: install hadoop master packages
      apt: pkg={{ item }} state=latest force=yes
      with_items:
        - hadoop-yarn-resourcemanager
        - hadoop-hdfs-namenode
    - name: copy configuration
      tags: deploy
      copy: src=files/mapred-site.xml dest=/etc/hadoop/conf.empty/ mode=0640 
      notify:
        - restart namenode
    - name: Pushes configuration
      template: src={{ item }} dest=/etc/hadoop/conf.empty/ mode=0640 owner=root group=root
      with_items:
        - templates/core-site.xml.j2
        - src=templates/yarn-site.xml.j2
      notify:
        - restart namenode
  handlers:
   - name: restart namenode
     service: name=hadoop-hdfs-namenode state=restarted
