- name: add ganglia monitoring
  hosts: hadoop
  gather_facts: yes
  roles:
   - ganglia-client
- name: configure hadoop master
  hosts: hadoopmaster
  gather_facts: yes
  roles:
   - { role: cloudera-master, blocksize: '10m',  blockreplication: 2 }
- name: configure hadoop slaves
  hosts: hadoopslave
  gather_facts: yes
  roles:
   - { role: cloudera-slave}
