#  with_items: group_names
- name: common roles
  hosts: all
  gather_facts: no
  roles:
   - { role: common }
- name: configure ganglia server
  hosts: gangliaserver
  gather_facts: no
  roles:
   - { role: ganglia, is_server: 'yes' }
- name: configure ganglia hub
  hosts: gangliahub
  gather_facts: no
  roles:
   - { role: ganglia}
- name: configure ganglia slaves
  hosts: gangliaclient
  gather_facts: no
  roles:
   - { role: ganglia}
